version: '3.8'
services:
  stats-server:
    build: ./stats-service
    image: stats_image
    container_name: stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore-stats
      - SPRING_DATASOURCE_USERNAME=explore-main
      - SPRING_DATASOURCE_PASSWORD=password
    restart: always

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=explore-stats
      - POSTGRES_USER=explore-main
      - POSTGRES_PASSWORD=password

  ewm-service:
    build: ./main-service
    image: main_image
    container_name: main
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - spring.datasource.url=jdbc:postgresql://ewm-db:5432/explore-main
      - SPRING_DATASOURCE_USERNAME=explore-main
      - SPRING_DATASOURCE_PASSWORD=password
    restart: always

  ewm-db:
    image: postgres:14-alpine
    container_name: main_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore-main
      - POSTGRES_USER=explore-main
      - POSTGRES_PASSWORD=password